export const mockResearchAnalytics = {
  overview: {
    total_faculty: 86,
    faculty_with_research: 58,
    total_research_papers: 214,
    total_projects: 37,
    total_patents: 12,
    total_books: 28,
    total_conferences: 96,
    total_funding: 18450000,
    total_vc_score: 842,
  },
  indexing: [
    { indexing: 'SCI / Web of Science', total_papers: 72, total_faculty: 31, vc_score: 318 },
    { indexing: 'Scopus', total_papers: 84, total_faculty: 38, vc_score: 296 },
    { indexing: 'UGC', total_papers: 36, total_faculty: 21, vc_score: 146 },
    { indexing: 'Other', total_papers: 16, total_faculty: 12, vc_score: 64 },
    { indexing: 'Not specified', total_papers: 6, total_faculty: 5, vc_score: 18 },
  ],
  faculty: {
    items: [
      {
        faculty_id: 1,
        faculty_name: 'Dr. Aditi Rao',
        employee_id: 'EMP001',
        email: 'aditi.rao@dypiu.ac.in',
        school: 'School of Engineering',
        department: 'Computer Science',
        total_research_papers: 18,
        sci_papers: 7,
        scopus_papers: 8,
        ugc_papers: 2,
        book_publications: 3,
        conference_publications: 9,
        patents: 2,
        research_projects: 4,
        total_funding: 3200000,
        total_vc_score: 86,
      },
      {
        faculty_id: 2,
        faculty_name: 'Prof. Rohan Mehta',
        employee_id: 'EMP014',
        email: 'rohan.mehta@dypiu.ac.in',
        school: 'School of Engineering',
        department: 'Data Science',
        total_research_papers: 15,
        sci_papers: 4,
        scopus_papers: 7,
        ugc_papers: 3,
        book_publications: 2,
        conference_publications: 8,
        patents: 1,
        research_projects: 3,
        total_funding: 2100000,
        total_vc_score: 72,
      },
      {
        faculty_id: 3,
        faculty_name: 'Dr. Nisha Kulkarni',
        employee_id: 'EMP026',
        email: 'nisha.kulkarni@dypiu.ac.in',
        school: 'School of Management',
        department: 'Business Analytics',
        total_research_papers: 13,
        sci_papers: 5,
        scopus_papers: 5,
        ugc_papers: 1,
        book_publications: 4,
        conference_publications: 6,
        patents: 0,
        research_projects: 2,
        total_funding: 1450000,
        total_vc_score: 65,
      },
    ],
    page: 1,
    page_size: 10,
    total: 3,
    total_pages: 1,
  },
  trend: [
    { year: 2021, total_papers: 28 },
    { year: 2022, total_papers: 34 },
    { year: 2023, total_papers: 42 },
    { year: 2024, total_papers: 51 },
    { year: 2025, total_papers: 59 },
  ],
  projects: [
    { group: 'funding_agency', name: 'AICTE', total: 8, amount: 4200000 },
    { group: 'funding_agency', name: 'DST', total: 5, amount: 6100000 },
    { group: 'funding_agency', name: 'Industry Sponsored', total: 11, amount: 5200000 },
    { group: 'project_type', name: 'Internal', total: 18, amount: 2600000 },
    { group: 'project_type', name: 'External', total: 19, amount: 15850000 },
  ],
  scores: {
    self_score: 1024,
    director_score: 942,
    dean_score: 896,
    vc_score: 842,
    reduced_by_director: 31,
    reduced_by_dean: 18,
    reduced_by_vc: 12,
    unchanged_records: 74,
  },
  topFaculty: [
    { faculty_id: 1, faculty_name: 'Dr. Aditi Rao', total_research_papers: 18 },
    { faculty_id: 2, faculty_name: 'Prof. Rohan Mehta', total_research_papers: 15 },
    { faculty_id: 3, faculty_name: 'Dr. Nisha Kulkarni', total_research_papers: 13 },
  ],
  topJournals: [
    { journal: 'IEEE Access', total: 12 },
    { journal: 'Springer LNNS', total: 9 },
    { journal: 'Elsevier Materials Today', total: 7 },
  ],
  filterOptions: {
    schools: ['School of Engineering', 'School of Management'],
    departments: ['Computer Science', 'Data Science', 'Business Analytics'],
    years: [2021, 2022, 2023, 2024, 2025],
    indexing_categories: ['SCI / Web of Science', 'Scopus', 'UGC', 'Other', 'Not specified'],
    project_statuses: ['Completed', 'Ongoing', 'Submitted', 'Sanctioned'],
    funding_agencies: ['AICTE', 'DST', 'Industry Sponsored'],
  },
}

export function mockFacultyDetail(facultyId) {
  const faculty = mockResearchAnalytics.faculty.items.find((item) => String(item.faculty_id) === String(facultyId))

  return {
    faculty,
    score_summary: mockResearchAnalytics.scores,
    year_wise_activity_trend: mockResearchAnalytics.trend,
    records: {
      journal_publications: [
        {
          title: 'Adaptive Learning Analytics for Outcome Based Education',
          journal: 'IEEE Access',
          issn: '2169-3536',
          journal_indexing: 'SCI Indexed',
          self_score: 10,
          director_score: 9,
          dean_score: 9,
          vc_score: 9,
          document: 'Uploaded',
        },
      ],
      book_publications: [{ title: 'Applied Analytics in Higher Education', publisher: 'Springer', vc_score: 8 }],
      conferences: [{ title: 'Faculty Research Impact Models', conference: 'ICACDS', vc_score: 6 }],
      patents: [{ title: 'Smart appraisal workflow system', status: 'Published', vc_score: 10 }],
      research_projects: [
        {
          project_title: 'AI enabled appraisal analytics',
          project_type: 'External',
          funding_agency: 'DST',
          amount: 1250000,
          role: 'Principal Investigator',
          status: 'Ongoing',
          vc_score: 12,
        },
      ],
      research_guidance: [{ scholar: 'M.Tech Research Group', status: 'Completed' }],
      awards: [{ title: 'Best Research Mentor', year: 2025 }],
    },
  }
}
